#-------------------------------------------------
#
# Project created by QtCreator 2021-04-11T20:41:28
#
#-------------------------------------------------

QT       += core gui xml network sql

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = XODRMaker
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

win32 {
    LIBS += C:/OSGeo4W64/lib/proj.lib
} else {
    LIBS += -lproj
}

INCLUDEPATH += ./_Utils

OTHER_FILES += \
    ./_Utils/DB/pg_dump.sql \
    ./OSM/Ref/Key_highway - OpenStreetMap Wiki.mhtml \
    ./XODR/OpenDRIVE/xsd/opendrive_16_core.xsd \
    ./XODR/OpenDRIVE/xsd/opendrive_16_junction.xsd \
    ./XODR/OpenDRIVE/xsd/opendrive_16_lane.xsd \
    ./XODR/OpenDRIVE/xsd/opendrive_16_object.xsd \
    ./XODR/OpenDRIVE/xsd/opendrive_16_railroad.xsd \
    ./XODR/OpenDRIVE/xsd/opendrive_16_road.xsd \
    ./XODR/OpenDRIVE/xsd/opendrive_16_signal.xsd \
    ./XODR/OpenDRIVE/manual/6.1. Coordinate systems overview.png \
    ./XODR/OpenDRIVE/manual/6.2. Inertial coordinate systems.png \
    ./XODR/OpenDRIVE/manual/6.3. Reference line coordinate systems.png \
    ./XODR/OpenDRIVE/manual/6.4. Local coordinate systems.png \
    ./XODR/OpenDRIVE/manual/6.5. Summary of all available coordinate systems.png \
    ./XODR/OpenDRIVE/manual/OpenDRIVE 1.6_files/font-awesome.min.css \
    ./XODR/OpenDRIVE/manual/OpenDRIVE 1.6.html \
    ./_Utils/DB/ReadMe.md \
    ./XODR/OpenDRIVE/manual/OpenDRIVE 1.6_files/MathJax.js.download \
    ./OSM/Ref/nodes_keys_only.txt \
    ./OSM/Ref/nodes_vals_200_20.txt \
    ./OSM/Node/OSMNodeTablesUpdateThread.txt \
    ./OSM/Way/OSMWayTablesUpdateThread.txt \
    ./OSM/Ref/ways_keys_only.txt \
    ./OSM/Ref/ways_vals_200_20.txt \
    ./OSM/Ref/ways_vals_200_20_shrinked.txt \
    ./OSM/Ref/ways_vals_highway_width.txt \
    ./OSM/Ref/ways_vals_highway_width_compacted.txt \
    ./OSM/Ref/ways_vals_highway_width_sorted.txt

FORMS += \
    ./_XODRMaker/CurvatureSlope/CurvatureSlopeTablesUpdateWnd.ui \
    ./_XODRMaker/GeoJSON/GeoJSONApplyingTestWnd.ui \
    ./_XODRMaker/GeoJSON/GeoJSONApplyingWnd.ui \
    ./_XODRMaker/GeoJSON/GeoJSONStagingUploadWnd.ui \
    ./_XODRMaker/GPS/GPSTablesUpdateWnd.ui \
    ./_XODRMaker/XODR/JSONFilesUpdateWnd.ui \
    ./_XODRMaker/Main/MainWnd.ui \
    ./_XODRMaker/Main/MapWnd.ui \
    ./_XODRMaker/Main/NavigateToLLDlg.ui \
    ./_XODRMaker/Main/NavigateToXYDlg.ui \
    ./_XODRMaker/CurvatureSlope/NewCurvatureSlopeDataChooseDlg.ui \
    ./_XODRMaker/GPS/NewGPSDataChooseDlg.ui \
    ./_XODRMaker/CountryArea/OSMCountryAreaTablesUpdateWnd.ui \
    ./_XODRMaker/Node/OSMNodeTablesUpdateWnd.ui \
    ./_XODRMaker/Way/OSMWayTablesUpdateWnd.ui \
    ./_XODRMaker/Main/SetLocalFilesDatabasePathDlg.ui \
    ./_XODRMaker/CountryArea/SetOSMCountryAreaSettingsDlg.ui \
    ./_XODRMaker/Node/SetOSMNodeSettingsDlg.ui \
    ./_XODRMaker/Way/SetOSMWaySettingsDlg.ui \
    ./_XODRMaker/Main/SetPGDatabaseSettingDlg.ui \
    ./_XODRMaker/Trajectory/TrajectoryTablesUpdateWnd.ui \
    ./_XODRMaker/XODR/XODRFilesUpdateWnd.ui \
    ./_XODRMaker/XODR/XODRTablesUpdateWnd.ui

HEADERS += \
    ./XODR/OpenDRIVE/core/_date.h \
    ./XODR/OpenDRIVE/core/_double.h \
    ./XODR/OpenDRIVE/core/_integer.h \
    ./XODR/OpenDRIVE/internal/_internal.h \
    ./XODR/OpenDRIVE/core/_OpenDriveElement.h \
    ./XODR/OpenDRIVE/core/_stringEnum.h \
    ./XODR/OpenDRIVE/lane/_t_road_lanes_laneSection_lcr.h \
    ./XODR/OpenDRIVE/lane/_t_road_lanes_laneSection_lcr_lane.h \
    ./XODR/OpenDRIVE/core/a_ds.h \
    ./XODR/OpenDRIVE/core/a_ds_polynom.h \
    ./XODR/OpenDRIVE/core/a_polynom.h \
    ./XODR/OpenDRIVE/core/a_s_polynom.h \
    ./XODR/OpenDRIVE/core/a_s_t_polynom.h \
    ./XODR/OpenDRIVE/core/a_sOffset.h \
    ./XODR/OpenDRIVE/core/a_sOffset_polynom.h \
    ./XODR/OpenDRIVE/core/a_sOffset_tOffset.h \
    ./XODR/OpenDRIVE/core/a_xy_hdg.h \
    ./_Utils/GeoCoordinate/Main/CardinalDirection.h \
    ./_Utils/GeoCoordinate/Main/Cell.h \
    ./_Utils/Math/Main/Clipper.h \
    ./_Utils/Math/Main/ClipperLL.h \
    ./_Utils/Math/Main/ClipperMacros.h \
    ./_Utils/Math/Main/ClipperXY.h \
    ./_Utils/Common/Common.h \
    ./_Utils/Common/Internal/Compile.h \
    ./_Utils/GeoCoordinate/Main/CoordSys.h \
    ./_Utils/GeoCoordinate/Main/CoordSysCell.h \
    ./_Utils/GeoCoordinate/Main/CoordSysXY.h \
    ./_Utils/GeoCoordinate/Main/CoordSysXYCell.h \
    ./CurvatureSlope/CurvatureSlopeTablesUpdateThread.h \
    ./_XODRMaker/CurvatureSlope/CurvatureSlopeTablesUpdateWnd.h \
    ./_Utils/DB/Main/DatabaseConnector.h \
    ./_Utils/DB/Main/DatabaseSettingsOnLocalSystem.h \
    ./_Utils/Common/Main/DateTime.h \
    ./_Utils/DB/DB.h \
    ./_Utils/Debugger/Debugger.h \
    ./_Utils/Common/Main/DefaultInstance.h \
    ./XODR/OpenDRIVE/lane/e_accessRestrictionType.h \
    ./XODR/OpenDRIVE/object/e_borderType.h \
    ./XODR/OpenDRIVE/object/e_bridgeType.h \
    ./XODR/OpenDRIVE/junction/e_contactPoint.h \
    ./XODR/OpenDRIVE/road/e_countryCode.h \
    ./XODR/OpenDRIVE/road/e_countryCode_deprecated.h \
    ./XODR/OpenDRIVE/road/e_countryCode_iso3166alpha2.h \
    ./XODR/OpenDRIVE/road/e_countryCode_iso3166alpha3_deprecated.h \
    ./XODR/OpenDRIVE/core/e_dataQuality_RawData_PostProcessing.h \
    ./XODR/OpenDRIVE/core/e_dataQuality_RawData_Source.h \
    ./XODR/OpenDRIVE/road/e_direction.h \
    ./XODR/OpenDRIVE/junction/e_elementDir.h \
    ./XODR/OpenDRIVE/junction/e_junction_type.h \
    ./XODR/OpenDRIVE/junction/e_junctionGroup_type.h \
    ./XODR/OpenDRIVE/lane/e_laneType.h \
    ./XODR/OpenDRIVE/road/e_maxSpeedString.h \
    ./XODR/OpenDRIVE/object/e_objectType.h \
    ./XODR/OpenDRIVE/object/e_orientation.h \
    ./XODR/OpenDRIVE/object/e_outlineFillType.h \
    ./XODR/OpenDRIVE/road/e_paramPoly3_pRange.h \
    ./XODR/OpenDRIVE/lane/e_road_lanes_laneSection_lcr_lane_roadMark_laneChange.h \
    ./XODR/OpenDRIVE/lane/e_road_lanes_laneSection_lr_lane_access_rule.h \
    ./XODR/OpenDRIVE/road/e_road_link_elementType.h \
    ./XODR/OpenDRIVE/object/e_road_objects_object_parkingSpace_access.h \
    ./XODR/OpenDRIVE/railroad/e_road_railroad_switch_position.h \
    ./XODR/OpenDRIVE/signal/e_road_signals_signal_reference_elementType.h \
    ./XODR/OpenDRIVE/signal/e_road_signals_signal_type.h \
    ./XODR/OpenDRIVE/junction/e_road_surface_CRG_mode.h \
    ./XODR/OpenDRIVE/junction/e_road_surface_CRG_purpose.h \
    ./XODR/OpenDRIVE/lane/e_roadMarkColor.h \
    ./XODR/OpenDRIVE/lane/e_roadMarkRule.h \
    ./XODR/OpenDRIVE/lane/e_roadMarkType.h \
    ./XODR/OpenDRIVE/lane/e_roadMarkWeight.h \
    ./XODR/OpenDRIVE/road/e_roadType.h \
    ./XODR/OpenDRIVE/object/e_sideType.h \
    ./XODR/OpenDRIVE/railroad/e_station_platform_segment_side.h \
    ./XODR/OpenDRIVE/railroad/e_station_type.h \
    ./XODR/OpenDRIVE/road/e_trafficRule.h \
    ./XODR/OpenDRIVE/object/e_tunnelType.h \
    ./XODR/OpenDRIVE/core/e_unit.h \
    ./XODR/OpenDRIVE/core/e_unitDistance.h \
    ./XODR/OpenDRIVE/core/e_unitMass.h \
    ./XODR/OpenDRIVE/core/e_unitSlope.h \
    ./XODR/OpenDRIVE/core/e_unitSpeed.h \
    ./Trajectory/EgoTrajectoryCreator.h \
    ./XODR/Main/ExternalSourceProvider.h \
    ./_Utils/Common/Main/File.h \
    ./XODR/Main/FileReader.h \
    ./XODR/OpenDRIVE/core/g_additionalData.h \
    ./_Utils/GeoCoordinate/GeoCoordinate.h \
    ./GeoJSON/GeoJSONApplyingTestThread.h \
    ./_XODRMaker/GeoJSON/GeoJSONApplyingTestWnd.h \
    ./GeoJSON/GeoJSONApplyingThread.h \
    ./_XODRMaker/GeoJSON/GeoJSONApplyingWnd.h \
    ./GeoJSON/GeoJSONStagingUploadThread.h \
    ./_XODRMaker/GeoJSON/GeoJSONStagingUploadWnd.h \
    ./_Utils/DB/Main/GlobalSettingsOnPGDatabase.h \
    ./GPS/GPSSettingsOnPGDatabase.h \
    ./GPS/GPSTablesUpdateThread.h \
    ./_XODRMaker/GPS/GPSTablesUpdateWnd.h \
    ./_Utils/Network/Main/HttpRequest.h \
    ./_Utils/Common/Internal/Internal.h \
    ./_Utils/DB/Internal/Internal.h \
    ./_Utils/Debugger/Internal/Internal.h \
    ./_Utils/GeoCoordinate/Internal/Internal.h \
    ./_Utils/Math/Internal/Internal.h \
    ./_Utils/Network/Internal/Internal.h \
    ./_Utils/SettingsOnLocalSystem/Internal/Internal.h \
    ./_Utils/Thread/Internal/Internal.h \
    ./_Utils/UniversialType/Internal/Internal.h \
    ./_Utils/XML/Internal/Internal.h \
    ./_XODRMaker/Internal/Internal.h \
    ./OSM/Internal/Internal.h \
    ./XODR/Internal/Internal.h \
    ./_Utils/Common/Main/JsonArray.h \
    ./XODR/Main/JSONFilesUpdateThread.h \
    ./_XODRMaker/XODR/JSONFilesUpdateWnd.h \
    ./Trajectory/KalmanFilter.h \
    ./_Utils/GeoCoordinate/Main/LL.h \
    ./_Utils/GeoCoordinate/Main/LLCoordSysXYCell.h \
    ./_Utils/DB/Main/LocalFilesDatabaseConnector.h \
    ./_Utils/DB/Main/LocalFilesDatabaseSettings.h \
    ./_Utils/Debugger/Main/Logger.h \
    ./_Utils/Debugger/Main/LoggingSlotManager.h \
    ./_Utils/Debugger/Main/LoggingTarget.h \
    ./_Utils/Debugger/Main/LoggingThread.h \
    ./_Utils/Debugger/Main/LogInfo.h \
    ./_XODRMaker/Main/MainWnd.h \
    ./_XODRMaker/Main/MapWnd.h \
    ./_Utils/Math/Math.h \
    ./XODR/Main/MeasurementContent.h \
    ./GPS/NativeGPSData.h \
    ./_XODRMaker/Main/NavigateToLLDlg.h \
    ./_XODRMaker/Main/NavigateToXYDlg.h \
    ./_Utils/Network/Network.h \
    ./_XODRMaker/CurvatureSlope/NewCurvatureSlopeDataChooseDlg.h \
    ./_XODRMaker/GPS/NewGPSDataChooseDlg.h \
    ./OSM/Node/Node.h \
    ./XODR/OpenDRIVE/core/OpenDRIVE.h \
    ./XODR/Main/OpenDRIVEBuilder.h \
    ./OSM/OSM.h \
    ./OSM/CountryArea/OSMCountryAreaSettingsOnPGDatabase.h \
    ./OSM/CountryArea/OSMCountryAreaTablesUpdateThread.h \
    ./_XODRMaker/CountryArea/OSMCountryAreaTablesUpdateWnd.h \
    ./XODR/Main/OSMExternalSourceProvider.h \
    ./OSM/Node/OSMNodeSettingsOnPGDatabase.h \
    ./OSM/Node/OSMNodeTablesUpdateThread.h \
    ./_XODRMaker/Node/OSMNodeTablesUpdateWnd.h \
    ./XODR/OSMToOD/OSMToOD.h \
    ./OSM/Way/OSMWaySettingsOnPGDatabase.h \
    ./OSM/Way/OSMWayTablesUpdateThread.h \
    ./_XODRMaker/Way/OSMWayTablesUpdateWnd.h \
    ./OSM/Main/OverpassAPI.h \
    ./_Utils/DB/Main/PGDatabaseConnector.h \
    ./OSM/Main/PolygonAPI.h \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider.h \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider__Base.h \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider__LHT.h \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider__RHT.h \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider_AU.h \
    ./_Utils/Math/Main/QMatrix4x4D.h \
    ./OSM/Main/RequestAnalyzer.h \
    ./OSM/Main/RequestLauncher.h \
    ./OSM/Main/RequestStatus.h \
    ./OSM/Main/ResultGenerator.h \
    ./XODR/Main/RoadFusor.h \
    ./_XODRMaker/Main/SetLocalFilesDatabasePathDlg.h \
    ./_XODRMaker/CountryArea/SetOSMCountryAreaSettingsDlg.h \
    ./_XODRMaker/Node/SetOSMNodeSettingsDlg.h \
    ./_XODRMaker/Way/SetOSMWaySettingsDlg.h \
    ./_XODRMaker/Main/SetPGDatabaseSettingDlg.h \
    ./_Utils/SettingsOnLocalSystem/Main/SettingsOnLocalSystem.h \
    ./_Utils/SettingsOnLocalSystem/SettingsOnLocalSystem.h \
    ./_Utils/DB/Main/SettingsOnPGDatabase.h \
    ./_Utils/Common/Main/String.h \
    ./_Utils/Common/Main/StringContants.h \
    ./_Utils/UniversialType/Main/StringPairs.h \
    ./XODR/OpenDRIVE/lane/t_bool_default_false.h \
    ./XODR/OpenDRIVE/lane/t_bool_default_true.h \
    ./XODR/OpenDRIVE/core/t_cell.h \
    ./XODR/OpenDRIVE/signal/t_controller.h \
    ./XODR/OpenDRIVE/signal/t_controller_control.h \
    ./XODR/OpenDRIVE/core/t_dataQuality.h \
    ./XODR/OpenDRIVE/core/t_dataQuality_Error.h \
    ./XODR/OpenDRIVE/core/t_dataQuality_RawData.h \
    ./XODR/OpenDRIVE/core/t_grEqZero.h \
    ./XODR/OpenDRIVE/core/t_grZero.h \
    ./XODR/OpenDRIVE/core/t_header.h \
    ./XODR/OpenDRIVE/core/t_header_GeoReference.h \
    ./XODR/OpenDRIVE/core/t_header_Offset.h \
    ./XODR/OpenDRIVE/core/t_include.h \
    ./XODR/OpenDRIVE/junction/t_junction.h \
    ./XODR/OpenDRIVE/junction/t_junction_connection.h \
    ./XODR/OpenDRIVE/junction/t_junction_connection_laneLink.h \
    ./XODR/OpenDRIVE/junction/t_junction_controller.h \
    ./XODR/OpenDRIVE/junction/t_junction_predecessorSuccessor.h \
    ./XODR/OpenDRIVE/junction/t_junction_priority.h \
    ./XODR/OpenDRIVE/junction/t_junction_surface.h \
    ./XODR/OpenDRIVE/junction/t_junction_surface_CRG.h \
    ./XODR/OpenDRIVE/junction/t_junctionGroup.h \
    ./XODR/OpenDRIVE/junction/t_junctionGroup_junctionReference.h \
    ./XODR/OpenDRIVE/road/t_maxSpeed.h \
    ./XODR/OpenDRIVE/road/t_road.h \
    ./XODR/OpenDRIVE/road/t_road_elevationProfile.h \
    ./XODR/OpenDRIVE/road/t_road_elevationProfile_elevation.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneOffset.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_center.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_center_lane.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lcr_lane_link.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lcr_lane_link_predecessorSuccessor.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lcr_lane_roadMark.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lcr_lane_roadMark_explicit.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lcr_lane_roadMark_explicit_line.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lcr_lane_roadMark_sway.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lcr_lane_roadMark_type.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lcr_lane_roadMark_type_line.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_left.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_left_lane.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lr_lane.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lr_lane_access.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lr_lane_border.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lr_lane_height.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lr_lane_material.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lr_lane_rule.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lr_lane_speed.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lr_lane_width.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_right.h \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_right_lane.h \
    ./XODR/OpenDRIVE/road/t_road_lateralProfile.h \
    ./XODR/OpenDRIVE/road/t_road_lateralProfile_shape.h \
    ./XODR/OpenDRIVE/road/t_road_lateralProfile_superelevation.h \
    ./XODR/OpenDRIVE/road/t_road_link.h \
    ./XODR/OpenDRIVE/road/t_road_link_predecessorSuccessor.h \
    ./XODR/OpenDRIVE/object/t_road_objects.h \
    ./XODR/OpenDRIVE/object/t_road_objects_bridge.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_borders.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_borders_border.h \
    ./XODR/OpenDRIVE/lane/t_road_objects_object_laneValidity.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_markings.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_markings_marking.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_markings_marking_cornerReference.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_material.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_outlines.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_outlines_outline.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_outlines_outline_cornerLocal.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_outlines_outline_cornerRoad.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_parkingSpace.h \
    ./XODR/OpenDRIVE/object/t_road_objects_object_repeat.h \
    ./XODR/OpenDRIVE/object/t_road_objects_objectReference.h \
    ./XODR/OpenDRIVE/object/t_road_objects_tunnel.h \
    ./XODR/OpenDRIVE/road/t_road_planView.h \
    ./XODR/OpenDRIVE/road/t_road_planView_geometry.h \
    ./XODR/OpenDRIVE/road/t_road_planView_geometry_arc.h \
    ./XODR/OpenDRIVE/road/t_road_planView_geometry_line.h \
    ./XODR/OpenDRIVE/road/t_road_planView_geometry_paramPoly3.h \
    ./XODR/OpenDRIVE/road/t_road_planView_geometry_poly3.h \
    ./XODR/OpenDRIVE/road/t_road_planView_geometry_spiral.h \
    ./XODR/OpenDRIVE/railroad/t_road_railroad.h \
    ./XODR/OpenDRIVE/railroad/t_road_railroad_switch.h \
    ./XODR/OpenDRIVE/railroad/t_road_railroad_switch_mainTrack.h \
    ./XODR/OpenDRIVE/railroad/t_road_railroad_switch_partner.h \
    ./XODR/OpenDRIVE/railroad/t_road_railroad_switch_sideTrack.h \
    ./XODR/OpenDRIVE/railroad/t_road_railroad_switch_track.h \
    ./XODR/OpenDRIVE/signal/t_road_signals.h \
    ./XODR/OpenDRIVE/signal/t_road_signals_signal.h \
    ./XODR/OpenDRIVE/signal/t_road_signals_signal_dependency.h \
    ./XODR/OpenDRIVE/signal/t_road_signals_signal_positionInertial.h \
    ./XODR/OpenDRIVE/signal/t_road_signals_signal_positionRoad.h \
    ./XODR/OpenDRIVE/signal/t_road_signals_signal_reference.h \
    ./XODR/OpenDRIVE/signal/t_road_signals_signalReference.h \
    ./XODR/OpenDRIVE/road/t_road_surface.h \
    ./XODR/OpenDRIVE/road/t_road_surface_CRG.h \
    ./XODR/OpenDRIVE/road/t_road_type.h \
    ./XODR/OpenDRIVE/road/t_road_type_speed.h \
    ./XODR/OpenDRIVE/railroad/t_station.h \
    ./XODR/OpenDRIVE/railroad/t_station_platform.h \
    ./XODR/OpenDRIVE/railroad/t_station_platform_segment.h \
    ./XODR/OpenDRIVE/core/t_userData.h \
    ./XODR/OpenDRIVE/core/t_yesNo.h \
    ./XODR/OpenDRIVE/core/t_zeroOne.h \
    ./_Utils/Thread/Main/Thread.h \
    ./_Utils/Thread/Thread.h \
    ./Trajectory/TrajectorySettingsOnPGDatabase.h \
    ./Trajectory/TrajectorySpliter.h \
    ./Trajectory/TrajectoryTablesUpdateThread.h \
    ./_XODRMaker/Trajectory/TrajectoryTablesUpdateWnd.h \
    ./_Utils/UniversialType/Main/UniversialType.h \
    ./_Utils/UniversialType/UniversialType.h \
    ./_Utils/DB/Main/UserSettingsOnPGDatabase.h \
    ./_Utils/Common/Main/Vector.h \
    ./_Utils/GeoCoordinate/Main/VehiclePos.h \
    ./OSM/Way/Way.h \
    ./_Utils/XML/XML.h \
    ./_Utils/XML/Main/XmlElement.h \
    ./_Utils/XML/Main/XmlStream.h \
    ./_Utils/XML/Main/XmlStream_p.h \
    ./_Utils/XML/Main/XmlUtils_p.h \
    ./XODR/XODR.h \
    ./XODR/Main/XODRFilesUpdateThread.h \
    ./_XODRMaker/XODR/XODRFilesUpdateWnd.h \
    ./XODR/Main/XODRSettingsOnPGDatabase.h \
    ./XODR/Main/XODRTablesUpdateThread.h \
    ./_XODRMaker/XODR/XODRTablesUpdateWnd.h \
    ./_Utils/Math/Main/XY.h \
    ./_Utils/GeoCoordinate/Main/XYCell.h \
    _Utils/Common/Main/Cacher.h

SOURCES += \
    ./XODR/OpenDRIVE/core/_core.cpp \
    ./XODR/OpenDRIVE/core/_date.cpp \
    ./XODR/OpenDRIVE/junction/_junction.cpp \
    ./XODR/OpenDRIVE/lane/_lane.cpp \
    ./XODR/OpenDRIVE/object/_object.cpp \
    ./XODR/OpenDRIVE/core/_OpenDriveElement.cpp \
    ./XODR/OpenDRIVE/railroad/_railroad.cpp \
    ./XODR/OpenDRIVE/road/_road.cpp \
    ./XODR/OpenDRIVE/signal/_signal.cpp \
    ./XODR/OpenDRIVE/core/a_ds.cpp \
    ./XODR/OpenDRIVE/core/a_sOffset.cpp \
    ./XODR/OpenDRIVE/core/a_sOffset_tOffset.cpp \
    ./_Utils/GeoCoordinate/Main/Cell.cpp \
    ./_Utils/GeoCoordinate/Main/CoordSys.cpp \
    ./_Utils/GeoCoordinate/Main/CoordSysCell.cpp \
    ./_Utils/GeoCoordinate/Main/CoordSysXY.cpp \
    ./_Utils/GeoCoordinate/Main/CoordSysXYCell.cpp \
    ./CurvatureSlope/CurvatureSlopeTablesUpdateThread.cpp \
    ./_XODRMaker/CurvatureSlope/CurvatureSlopeTablesUpdateWnd.cpp \
    ./_Utils/DB/Main/DatabaseConnector.cpp \
    ./_Utils/DB/Main/DatabaseSettingsOnLocalSystem.cpp \
    ./Trajectory/EgoTrajectoryCreator.cpp \
    ./_Utils/GeoCoordinate/GeoCoordinate.cpp \
    ./GeoJSON/GeoJSONApplyingTestThread.cpp \
    ./_XODRMaker/GeoJSON/GeoJSONApplyingTestWnd.cpp \
    ./GeoJSON/GeoJSONApplyingThread.cpp \
    ./_XODRMaker/GeoJSON/GeoJSONApplyingWnd.cpp \
    ./GeoJSON/GeoJSONStagingUploadThread.cpp \
    ./_XODRMaker/GeoJSON/GeoJSONStagingUploadWnd.cpp \
    ./_Utils/DB/Main/GlobalSettingsOnPGDatabase.cpp \
    ./GPS/GPSSettingsOnPGDatabase.cpp \
    ./GPS/GPSTablesUpdateThread.cpp \
    ./_XODRMaker/GPS/GPSTablesUpdateWnd.cpp \
    ./XODR/Main/JSONFilesUpdateThread.cpp \
    ./_XODRMaker/XODR/JSONFilesUpdateWnd.cpp \
    ./Trajectory/KalmanFilter.cpp \
    ./_Utils/GeoCoordinate/Main/LL.cpp \
    ./_Utils/GeoCoordinate/Main/LLCoordSysXYCell.cpp \
    ./_Utils/DB/Main/LocalFilesDatabaseConnector.cpp \
    ./_Utils/DB/Main/LocalFilesDatabaseSettings.cpp \
    ./_Utils/Debugger/Main/Logger.cpp \
    ./_Utils/Debugger/Main/LoggingSlotManager.cpp \
    ./_Utils/Debugger/Main/LoggingThread.cpp \
    ./_XODRMaker/Main/main.cpp \
    ./_XODRMaker/Main/MainWnd.cpp \
    ./_XODRMaker/Main/MapWnd.cpp \
    ./_Utils/Math/Math.cpp \
    ./_XODRMaker/Main/NavigateToLLDlg.cpp \
    ./_XODRMaker/Main/NavigateToXYDlg.cpp \
    ./_XODRMaker/CurvatureSlope/NewCurvatureSlopeDataChooseDlg.cpp \
    ./_XODRMaker/GPS/NewGPSDataChooseDlg.cpp \
    ./OSM/Node/Node.cpp \
    ./XODR/OpenDRIVE/core/OpenDRIVE.cpp \
    ./XODR/Main/OpenDRIVEBuilder.cpp \
    ./OSM/OSM.cpp \
    ./OSM/CountryArea/OSMCountryAreaSettingsOnPGDatabase.cpp \
    ./OSM/CountryArea/OSMCountryAreaTablesUpdateThread.cpp \
    ./_XODRMaker/CountryArea/OSMCountryAreaTablesUpdateWnd.cpp \
    ./XODR/Main/OSMExternalSourceProvider.cpp \
    ./OSM/Node/OSMNodeSettingsOnPGDatabase.cpp \
    ./OSM/Node/OSMNodeTablesUpdateThread.cpp \
    ./_XODRMaker/Node/OSMNodeTablesUpdateWnd.cpp \
    ./XODR/OSMToOD/OSMToOD.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_Lane.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_Lane_Bidirectional_MultiLanes.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_Lane_Bidirectional_OneLane.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_Lane_Oneway.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_LaneAccess.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_LaneAttrSubTags.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_LaneHeight.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_LaneMaterial.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_LaneRoadMark.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_LaneRule.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_LaneSpeed.cpp \
    ./XODR/OSMToOD/Lane/OSMToOD_LaneWidth.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_BARRIER.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_BIKE.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_BUILDING.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_BUS.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_CAR.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_CROSSWALK.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_GANTRY.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_MOTORBIKE.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_OBSTACLE.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_PARKINGSPACE.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_PATCH.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_PEDESTRIAN.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_POLE.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_RAILING.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_ROADMARK.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_SOUNDBARRIER.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_STREETLAMP.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_TRAFFICISLAND.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_TRAILER.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_TRAIN.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_TRAM.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_TREE.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_VAN.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_VEGETATION.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Object_WIND.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Node_Signal.cpp \
    ./XODR/OSMToOD/Node/OSMToOD_Nodes.cpp \
    ./XODR/OSMToOD/Road/OSMToOD_RoadAttrSubTags.cpp \
    ./XODR/OSMToOD/Road/OSMToOD_RoadElevationProfile.cpp \
    ./XODR/OSMToOD/Road/OSMToOD_RoadType.cpp \
    ./XODR/OSMToOD/Road/OSMToOD_RoadTypeSpeed.cpp \
    ./OSM/Way/OSMWaySettingsOnPGDatabase.cpp \
    ./OSM/Way/OSMWayTablesUpdateThread.cpp \
    ./_XODRMaker/Way/OSMWayTablesUpdateWnd.cpp \
    ./OSM/Main/OverpassAPI.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector.inl \
    ./_Utils/DB/Main/PGDatabaseConnector_Data_Status.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_GeoJSONApplying.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_GeoJSONStaging.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_GPS.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_Logs.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_OSMCountryArea.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_OSMNode.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_OSMWay.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_Settings.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_Trajectory.cpp \
    ./_Utils/DB/Main/PGDatabaseConnector_XODR.cpp \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider.cpp \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider__Base.cpp \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider__LHT.cpp \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider__RHT.cpp \
    ./OSM/PriorKnowledgeProvider/PriorKnowledgeProvider_AU.cpp \
    ./_Utils/Math/Main/QMatrix4x4D.cpp \
    ./OSM/Main/RequestAnalyzer.cpp \
    ./OSM/Main/RequestLauncher.cpp \
    ./OSM/Main/ResultGenerator.cpp \
    ./XODR/Main/RoadFusor.cpp \
    ./_XODRMaker/Main/SetLocalFilesDatabasePathDlg.cpp \
    ./_XODRMaker/CountryArea/SetOSMCountryAreaSettingsDlg.cpp \
    ./_XODRMaker/Node/SetOSMNodeSettingsDlg.cpp \
    ./_XODRMaker/Way/SetOSMWaySettingsDlg.cpp \
    ./_XODRMaker/Main/SetPGDatabaseSettingDlg.cpp \
    ./_Utils/SettingsOnLocalSystem/Main/SettingsOnLocalSystem.cpp \
    ./_Utils/DB/Main/SettingsOnPGDatabase.cpp \
    ./XODR/OpenDRIVE/core/t_header.cpp \
    ./XODR/OpenDRIVE/road/t_road.cpp \
    ./XODR/OpenDRIVE/lane/t_road_lanes.cpp \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection.cpp \
    ./XODR/OpenDRIVE/lane/t_road_lanes_laneSection_lr_lane.cpp \
    ./XODR/OpenDRIVE/object/t_road_objects_object_markings_marking.cpp \
    ./XODR/OpenDRIVE/road/t_road_planView.cpp \
    ./XODR/OpenDRIVE/road/t_road_planView_geometry.cpp \
    ./XODR/OpenDRIVE/road/t_road_surface_CRG.cpp \
    ./XODR/OpenDRIVE/railroad/t_station_platform_segment.cpp \
    ./XODR/OpenDRIVE/core/t_userData.cpp \
    ./_Utils/Thread/Main/Thread.cpp \
    ./Trajectory/TrajectorySettingsOnPGDatabase.cpp \
    ./Trajectory/TrajectorySpliter.cpp \
    ./Trajectory/TrajectoryTablesUpdateThread.cpp \
    ./_XODRMaker/Trajectory/TrajectoryTablesUpdateWnd.cpp \
    ./_Utils/DB/Main/UserSettingsOnPGDatabase.cpp \
    ./_Utils/GeoCoordinate/Main/VehiclePos.cpp \
    ./OSM/Way/Way.cpp \
    ./OSM/Way/Way_Junction.cpp \
    ./OSM/Way/Way_LaneCount1.cpp \
    ./OSM/Way/Way_LaneCount2.cpp \
    ./OSM/Way/Way_LanesWidth.cpp \
    ./OSM/Way/Way_Oneway.cpp \
    ./OSM/Way/Way_RoadMark.cpp \
    ./_Utils/XML/Main/XmlElement.cpp \
    ./_Utils/XML/Main/XmlStream.cpp \
    ./_Utils/XML/Main/XmlUtils.cpp \
    ./XODR/Main/XODRFilesUpdateThread.cpp \
    ./_XODRMaker/XODR/XODRFilesUpdateWnd.cpp \
    ./XODR/Main/XODRSettingsOnPGDatabase.cpp \
    ./XODR/Main/XODRTablesUpdateThread.cpp \
    ./_XODRMaker/XODR/XODRTablesUpdateWnd.cpp \
    ./_Utils/GeoCoordinate/Main/XYCell.cpp
